### This Notebook I'll drop the train data which it's churn rate is -1

In [1]:
import pandas as pd

In [49]:
train = pd.read_csv(r'dataset/train.csv')
test = pd.read_csv(r'dataset/test.csv')
test1 = pd.read_csv(r'dataset/test.csv')
sample = pd.read_csv(r'dataset/sample_submission.csv')

In [3]:
train.churn_risk_score.value_counts()

 3    10424
 4    10185
 5     9827
 2     2741
 1     2652
-1     1163
Name: churn_risk_score, dtype: int64

In [4]:
train_data = train[train['churn_risk_score'] > 0]

In [5]:
train_data

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,...,300.630000,53005.25,17.0,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,...,306.340000,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,...,516.160000,21027.00,22.0,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,...,53.270000,25239.56,6.0,567.660000,No,Yes,Yes,Unsolved,Poor Website,5
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,...,113.130000,24483.66,16.0,663.060000,No,Yes,Yes,Solved,Poor Website,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36987,fffe43004900440035003500390036003100,Cuc Tarr,46,F,6F51HFO,NaN,Basic Membership,2017-09-21,No,xxxxxxxx,...,-650.682759,27277.68,6.0,639.510000,No,Yes,Yes,No Information Available,No reason specified,4
36988,fffe43004900440033003500380036003600,Jenni Stronach,29,F,21KSM8Y,Town,Basic Membership,2016-06-27,No,xxxxxxxx,...,-638.123421,11069.71,28.0,527.990000,Yes,No,No,Not Applicable,Poor Customer Service,5
36989,fffe4300490044003500330034003100,Luciana Kinch,23,F,XK1IM9H,NaN,Basic Membership,2016-09-11,Yes,CID3838,...,154.940000,38127.56,Error,680.470000,No,Yes,Yes,Unsolved,Poor Website,4
36990,fffe43004900440031003200390039003000,Tawana Ardoin,53,M,K6VTP1Z,Village,Platinum Membership,2017-06-15,No,xxxxxxxx,...,482.610000,2378.86,20.0,197.264414,Yes,Yes,No,Not Applicable,No reason specified,3
36991,fffe43004900440033003600340034003200,Verlene Beaulieu,35,M,LBX0GLR,Town,Silver Membership,2015-10-23,No,xxxxxxxx,...,79.180000,2189.68,Error,719.970000,Yes,No,No,Not Applicable,Quality Customer Care,2

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35829 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   35829 non-null  object
 1   Name                          35829 non-null  object
 2   age                           35829 non-null  int64
 3   gender                        35829 non-null  object
 4   security_no                   35829 non-null  object
 5   region_category               30566 non-null  object
 6   membership_category           35829 non-null  object
 7   joining_date                  35829 non-null  object
 8   joined_through_referral       35829 non-null  object
 9   referral_id                   35829 non-null  object
 10  preferred_offer_types         35553 non-null  object
 11  medium_of_operation           35829 non-null  object
 12  internet_option               35829 non-null  object
 13  last_visit_time               35829 non-null  object
 14  days_since_last_login         35829 non-null  int64
 15  avg_time_spent                35829 non-null  float64
 16  avg_transaction_value         35829 non-null  float64
 17  avg_frequency_login_days      35829 non-null  object
 18  points_in_wallet              32488 non-null  float64
 19  used_special_discount         35829 non-null  object
 20  offer_application_preference  35829 non-null  object
 21  past_complaint                35829 non-null  object
 22  complaint_status              35829 non-null  object
 23  feedback                      35829 non-null  object
 24  churn_risk_score              35829 non-null  int64
dtypes: float64(3), int64(3), object(19)
memory usage: 7.1+ MB

In [7]:
train_y = train_data.churn_risk_score.copy()
train_x = train_data.drop('churn_risk_score', axis=1).copy()

### I will drop customer_id, name, security_code, referral_id, security_no

In [8]:
drop_list = ['customer_id', 'Name', 'referral_id', 'security_no']

for x in drop_list:
    train_x.drop(x, axis=1, inplace=True)
    test.drop(x, axis=1, inplace=True)

In [9]:
num_col = [x for x in train_x.columns if train_x[x].dtypes == 'int64' or train_x[x].dtypes == 'float64']

In [10]:
num_col

['age',
 'days_since_last_login',
 'avg_time_spent',
 'avg_transaction_value',
 'points_in_wallet']

In [11]:
cat_col = [x for x in train_x.columns if train_x[x].dtypes == 'O']

In [12]:
cat_col

['gender',
 'region_category',
 'membership_category',
 'joining_date',
 'joined_through_referral',
 'preferred_offer_types',
 'medium_of_operation',
 'internet_option',
 'last_visit_time',
 'avg_frequency_login_days',
 'used_special_discount',
 'offer_application_preference',
 'past_complaint',
 'complaint_status',
 'feedback']

In [13]:
train_x

,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback
0,18,F,Village,Platinum Membership,2017-08-17,No,Gift Vouchers/Coupons,?,Wi-Fi,16:08:02,17,300.630000,53005.25,17.0,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock
1,32,F,City,Premium Membership,2017-08-28,?,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,16,306.340000,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care
2,44,F,Town,No Membership,2016-11-11,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,14,516.160000,21027.00,22.0,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website
3,37,M,City,No Membership,2016-10-29,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,11,53.270000,25239.56,6.0,567.660000,No,Yes,Yes,Unsolved,Poor Website
4,31,F,City,No Membership,2017-09-12,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,20,113.130000,24483.66,16.0,663.060000,No,Yes,Yes,Solved,Poor Website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36987,46,F,NaN,Basic Membership,2017-09-21,No,Credit/Debit Card Offers,Desktop,Wi-Fi,04:14:05,2,-650.682759,27277.68,6.0,639.510000,No,Yes,Yes,No Information Available,No reason specified
36988,29,F,Town,Basic Membership,2016-06-27,No,Without Offers,Smartphone,Wi-Fi,23:18:31,13,-638.123421,11069.71,28.0,527.990000,Yes,No,No,Not Applicable,Poor Customer Service
36989,23,F,NaN,Basic Membership,2016-09-11,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,03:50:25,12,154.940000,38127.56,Error,680.470000,No,Yes,Yes,Unsolved,Poor Website
36990,53,M,Village,Platinum Membership,2017-06-15,No,Gift Vouchers/Coupons,Smartphone,Mobile_Data,09:50:03,15,482.610000,2378.86,20.0,197.264414,Yes,Yes,No,Not Applicable,No reason specified
36991,35,M,Town,Silver Membership,2015-10-23,No,Gift Vouchers/Coupons,Desktop,Mobile_Data,01:39:52,15,79.180000,2189.68,Error,719.970000,Yes,No,No,Not Applicable,Quality Customer Care

In [14]:
train_x.nunique()

age                                55
gender                              3
region_category                     3
membership_category                 6
joining_date                     1096
joined_through_referral             3
preferred_offer_types               3
medium_of_operation                 4
internet_option                     3
last_visit_time                 29329
days_since_last_login              27
avg_time_spent                  25299
avg_transaction_value           35741
avg_frequency_login_days         1587
points_in_wallet                23161
used_special_discount               2
offer_application_preference        2
past_complaint                      2
complaint_status                    5
feedback                            9
dtype: int64

In [15]:
test.nunique()

age                                55
gender                              3
region_category                     3
membership_category                 6
joining_date                     1096
joined_through_referral             3
preferred_offer_types               3
medium_of_operation                 4
internet_option                     3
last_visit_time                 17821
days_since_last_login              27
avg_time_spent                  15703
avg_transaction_value           19883
avg_frequency_login_days          946
points_in_wallet                14581
used_special_discount               2
offer_application_preference        2
past_complaint                      2
complaint_status                    5
feedback                            9
dtype: int64

In [16]:
train_y.shape

(35829,)

In [17]:
train_x.isna().sum()

age                                0
gender                             0
region_category                 5263
membership_category                0
joining_date                       0
joined_through_referral            0
preferred_offer_types            276
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                3341
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
dtype: int64

In [18]:
test.isna().sum()

age                                0
gender                             0
region_category                 2948
membership_category                0
joining_date                       0
joined_through_referral            0
preferred_offer_types            159
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                1963
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
dtype: int64

### We will fill the missing value

How to using value_counts() with nan value

### Region category

In [19]:
train_x.region_category.value_counts(dropna=False)

Town       13702
City       12315
NaN         5263
Village     4549
Name: region_category, dtype: int64

In [20]:
test.region_category.value_counts(dropna=False)

Town       7635
City       6792
NaN        2948
Village    2544
Name: region_category, dtype: int64

In [21]:
train_x.region_category.fillna('Town', inplace=True)
test.region_category.fillna('Town', inplace=True)

### Prefered offer types

In [22]:
train_x.preferred_offer_types.value_counts(dropna=False)

Gift Vouchers/Coupons       11977
Credit/Debit Card Offers    11860
Without Offers              11716
NaN                           276
Name: preferred_offer_types, dtype: int64

In [23]:
test.preferred_offer_types.value_counts(dropna=False)

Without Offers              6663
Credit/Debit Card Offers    6602
Gift Vouchers/Coupons       6495
NaN                          159
Name: preferred_offer_types, dtype: int64

In [24]:
train_x.preferred_offer_types.fillna('Gift Vouchers/Coupons', inplace=True)
test.preferred_offer_types.fillna('Gift Vouchers/Coupons', inplace=True)

### Points in wallet

In [25]:
train_x.points_in_wallet.value_counts(dropna=False)

NaN            3341
705.070000        9
780.920000        8
760.540000        7
771.750000        7
               ...
1213.463163       1
744.640000        1
779.760000        1
253.786598        1
677.660000        1
Name: points_in_wallet, Length: 23162, dtype: int64

In [26]:
p_wallet = train_x.points_in_wallet.median()

In [27]:
train_x.points_in_wallet.fillna(p_wallet, inplace=True)
test.points_in_wallet.fillna(p_wallet, inplace=True)

## Another analysis

In [28]:
train_x

,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback
0,18,F,Village,Platinum Membership,2017-08-17,No,Gift Vouchers/Coupons,?,Wi-Fi,16:08:02,17,300.630000,53005.25,17.0,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock
1,32,F,City,Premium Membership,2017-08-28,?,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,16,306.340000,12838.38,10.0,697.820000,Yes,No,Yes,Solved,Quality Customer Care
2,44,F,Town,No Membership,2016-11-11,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,14,516.160000,21027.00,22.0,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website
3,37,M,City,No Membership,2016-10-29,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,11,53.270000,25239.56,6.0,567.660000,No,Yes,Yes,Unsolved,Poor Website
4,31,F,City,No Membership,2017-09-12,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,20,113.130000,24483.66,16.0,663.060000,No,Yes,Yes,Solved,Poor Website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36987,46,F,Town,Basic Membership,2017-09-21,No,Credit/Debit Card Offers,Desktop,Wi-Fi,04:14:05,2,-650.682759,27277.68,6.0,639.510000,No,Yes,Yes,No Information Available,No reason specified
36988,29,F,Town,Basic Membership,2016-06-27,No,Without Offers,Smartphone,Wi-Fi,23:18:31,13,-638.123421,11069.71,28.0,527.990000,Yes,No,No,Not Applicable,Poor Customer Service
36989,23,F,Town,Basic Membership,2016-09-11,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,03:50:25,12,154.940000,38127.56,Error,680.470000,No,Yes,Yes,Unsolved,Poor Website
36990,53,M,Village,Platinum Membership,2017-06-15,No,Gift Vouchers/Coupons,Smartphone,Mobile_Data,09:50:03,15,482.610000,2378.86,20.0,197.264414,Yes,Yes,No,Not Applicable,No reason specified
36991,35,M,Town,Silver Membership,2015-10-23,No,Gift Vouchers/Coupons,Desktop,Mobile_Data,01:39:52,15,79.180000,2189.68,Error,719.970000,Yes,No,No,Not Applicable,Quality Customer Care

In [29]:
train_x.nunique()

age                                55
gender                              3
region_category                     3
membership_category                 6
joining_date                     1096
joined_through_referral             3
preferred_offer_types               3
medium_of_operation                 4
internet_option                     3
last_visit_time                 29329
days_since_last_login              27
avg_time_spent                  25299
avg_transaction_value           35741
avg_frequency_login_days         1587
points_in_wallet                23161
used_special_discount               2
offer_application_preference        2
past_complaint                      2
complaint_status                    5
feedback                            9
dtype: int64

In [30]:
train_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35829 entries, 0 to 36991
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           35829 non-null  int64
 1   gender                        35829 non-null  object
 2   region_category               35829 non-null  object
 3   membership_category           35829 non-null  object
 4   joining_date                  35829 non-null  object
 5   joined_through_referral       35829 non-null  object
 6   preferred_offer_types         35829 non-null  object
 7   medium_of_operation           35829 non-null  object
 8   internet_option               35829 non-null  object
 9   last_visit_time               35829 non-null  object
 10  days_since_last_login         35829 non-null  int64
 11  avg_time_spent                35829 non-null  float64
 12  avg_transaction_value         35829 non-null  float64
 13  avg_frequency_login_days      35829 non-null  object
 14  points_in_wallet              35829 non-null  float64
 15  used_special_discount         35829 non-null  object
 16  offer_application_preference  35829 non-null  object
 17  past_complaint                35829 non-null  object
 18  complaint_status              35829 non-null  object
 19  feedback                      35829 non-null  object
dtypes: float64(3), int64(2), object(15)
memory usage: 5.7+ MB

In [31]:
train_x.gender.unique()

array(['F', 'M', 'Unknown'], dtype=object)

In [32]:
low_car = [x for x in train_x.columns if (train_x[x].nunique() < 10)]

In [33]:
for x in low_car:
    print(x , " : ", train_x[x].unique())

gender  :  ['F' 'M' 'Unknown']
region_category  :  ['Village' 'City' 'Town']
membership_category  :  ['Platinum Membership' 'Premium Membership' 'No Membership'
 'Gold Membership' 'Silver Membership' 'Basic Membership']
joined_through_referral  :  ['No' '?' 'Yes']
preferred_offer_types  :  ['Gift Vouchers/Coupons' 'Credit/Debit Card Offers' 'Without Offers']
medium_of_operation  :  ['?' 'Desktop' 'Smartphone' 'Both']
internet_option  :  ['Wi-Fi' 'Mobile_Data' 'Fiber_Optic']
used_special_discount  :  ['Yes' 'No']
offer_application_preference  :  ['Yes' 'No']
past_complaint  :  ['No' 'Yes']
complaint_status  :  ['Not Applicable' 'Solved' 'Solved in Follow-up' 'Unsolved'
 'No Information Available']
feedback  :  ['Products always in Stock' 'Quality Customer Care' 'Poor Website'
 'No reason specified' 'Poor Product Quality' 'Poor Customer Service'
 'Too many ads' 'User Friendly Website' 'Reasonable Price']

In [34]:
for x in low_car:
    print(x , " : ", test[x].unique())

gender  :  ['F' 'M' 'Unknown']
region_category  :  ['Village' 'Town' 'City']
membership_category  :  ['Premium Membership' 'Gold Membership' 'Silver Membership'
 'No Membership' 'Basic Membership' 'Platinum Membership']
joined_through_referral  :  ['No' 'Yes' '?']
preferred_offer_types  :  ['Without Offers' 'Gift Vouchers/Coupons' 'Credit/Debit Card Offers']
medium_of_operation  :  ['Smartphone' 'Desktop' 'Both' '?']
internet_option  :  ['Wi-Fi' 'Fiber_Optic' 'Mobile_Data']
used_special_discount  :  ['Yes' 'No']
offer_application_preference  :  ['No' 'Yes']
past_complaint  :  ['No' 'Yes']
complaint_status  :  ['Not Applicable' 'Solved in Follow-up' 'No Information Available'
 'Unsolved' 'Solved']
feedback  :  ['Poor Product Quality' 'Poor Website' 'No reason specified'
 'Too many ads' 'Reasonable Price' 'Poor Customer Service'
 'User Friendly Website' 'Products always in Stock'
 'Quality Customer Care']

### Make average time absolute

In [35]:
train_x[num_col].describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet
count,35829.000000,35829.000000,35829.000000,35829.000000,35829.000000
mean,37.120266,-42.143906,243.373859,29304.272306,687.872239
std,15.865360,229.254856,397.784650,19484.565419,185.307833
min,10.000000,-999.000000,-2814.109110,800.460000,-760.661236
25%,23.000000,8.000000,59.810000,14194.650000,624.310000
50%,37.000000,12.000000,161.620000,27584.530000,697.820000
75%,51.000000,16.000000,356.330000,40874.010000,757.090000
max,64.000000,26.000000,3235.578521,99914.050000,2069.069761

In [36]:
test.describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet
count,19919.000000,19919.000000,19919.000000,19919.000000,19919.000000
mean,36.884432,-39.216527,244.134926,29318.122196,687.136720
std,15.917311,223.274420,403.910806,19507.775429,182.472892
min,10.000000,-999.000000,-2180.780796,803.710000,-465.289977
25%,23.000000,8.000000,59.360000,14236.200000,624.480000
50%,37.000000,12.000000,161.240000,27564.050000,697.820000
75%,51.000000,16.000000,354.195000,40969.400000,757.855000
max,64.000000,26.000000,3350.060000,99995.030000,2019.671602

In [37]:
train_x["days_since_last_login"] = train_x.days_since_last_login.abs()
train_x["avg_time_spent"] = train_x.avg_time_spent.abs()
train_x["points_in_wallet"] = train_x.points_in_wallet.abs()

test["days_since_last_login"] = test.days_since_last_login.abs()
test["avg_time_spent"] = test.avg_time_spent.abs()
test["points_in_wallet"] = test.points_in_wallet.abs()

In [38]:
train_x[num_col].describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet
count,35829.000000,35829.000000,35829.000000,35829.000000,35829.000000
mean,37.120266,66.263027,314.522508,29304.272306,689.128177
std,15.865360,223.479386,344.293403,19484.565419,180.581054
min,10.000000,1.000000,1.837399,800.460000,0.788907
25%,23.000000,9.000000,75.240000,14194.650000,624.310000
50%,37.000000,13.000000,186.020000,27584.530000,697.820000
75%,51.000000,18.000000,415.960000,40874.010000,757.090000
max,64.000000,999.000000,3235.578521,99914.050000,2069.069761

### Scaling

In [39]:
from sklearn.preprocessing import StandardScaler

scl = StandardScaler()

train_x_scl = scl.fit_transform(train_x[num_col])
test_scl = scl.transform(test[num_col])

array([[-1.20517486, -0.22043964, -0.04035135,  1.21641453,  0.51291713],
       [-0.32273691, -0.22491438, -0.02376642, -0.84508542,  0.0481332 ],
       [ 0.43363847, -0.23386388,  0.58566416, -0.42481768, -1.0435248 ],
       ...,
       [-0.89001845, -0.24281338, -0.46351378,  0.45284104, -0.04794688],
       [ 1.00092001, -0.22938913,  0.48821684, -1.38190344, -2.7238219 ],
       [-0.13364307, -0.22938913, -0.68356173, -1.3916128 ,  0.17079451]])

### Try Linear SVC

Use train_x_scl, train_y, test_scl

In [41]:
from sklearn.svm import SVC
svc_cl = SVC()

In [42]:
#svc_cl.fit(train_x_scl, train_y)

SVC()

In [44]:
svc_name = 'svc_cl_num.pkl'
import joblib as jb

#jb.dump(svc_cl, svc_name)
svc_clf = jb.load(svc_name)

In [50]:
def make_csv(predict, name):
    df = pd.DataFrame()
    df['customer_id'] = test1['customer_id']
    df['churn_risk_score'] = predict
    
    df.to_csv(name, index=False)

In [47]:
pred1 = svc_clf.predict(test_scl)

In [51]:
make_csv(pred1, 'submission_num.csv')

In [52]:
sub_num = pd.read_csv('submission_num.csv')

In [54]:
sub_num.churn_risk_score.value_counts()

3    7470
4    7022
5    4052
2     693
1     682
Name: churn_risk_score, dtype: int64

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
cross_score = cross_val_score(svc_clf, train_x_scl, train_y, cv=3, scoring='accuracy')

In [57]:
cross_score

array([0.58687097, 0.59432303, 0.59298334])

### try neural network

In [65]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(random_state=1)

In [66]:
clf.fit(train_x_scl, train_y)

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(random_state=1)

In [ ]:
'''nn_name = 'nn_clf_num.pkl'
import joblib as jb

jb.dump(clf, nn_name)
svc_clf = jb.load(nn_name)'''

In [68]:
pred2 = clf.predict(test_scl)

In [69]:
#make_csv(pred2, 'sub_num2.csv')